[package]
name = "enum_str"
version = "0.2.0"
authors = ["Raine Godmaire <its@raine.ing>"]
description = "Macro for creating a string-associated enum"
license = "MIT/Apache-2.0"
edition = "2021"

repository = "https://github.com/digyx/enum_str"
keywords = ["enum", "macro", "string"]
